redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/mac/Desktop/projects/SAULTECH/gigs/gighub/frontend/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/mac/Desktop/projects/SAULTECH/gigs/gighub/frontend"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]