export interface Option {
  label: string;
  value: string;
}

export const countries: Option[] = [
  { label: "Afghanistan", value: "Afghanistan" },
  { label: "Albania", value: "Albania" },
  { label: "Algeria", value: "Algeria" },
  { label: "Andorra", value: "Andorra" },
  { label: "Angola", value: "Angola" },
  { label: "Antigua and Barbuda", value: "Antigua and Barbuda" },
  { label: "Argentina", value: "Argentina" },
  { label: "Armenia", value: "Armenia" },
  { label: "Australia", value: "Australia" },
  { label: "Austria", value: "Austria" },
  { label: "Azerbaijan", value: "Azerbaijan" },
  { label: "Bahamas", value: "Bahamas" },
  { label: "Bahrain", value: "Bahrain" },
  { label: "Bangladesh", value: "Bangladesh" },
  { label: "Barbados", value: "Barbados" },
  { label: "Belarus", value: "Belarus" },
  { label: "Belgium", value: "Belgium" },
  { label: "Belize", value: "Belize" },
  { label: "Benin", value: "Benin" },
  { label: "Bhutan", value: "Bhutan" },
  { label: "Bolivia", value: "Bolivia" },
  { label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
  { label: "Botswana", value: "Botswana" },
  { label: "Brazil", value: "Brazil" },
  { label: "Brunei", value: "Brunei" },
  { label: "Bulgaria", value: "Bulgaria" },
  { label: "Burkina Faso", value: "Burkina Faso" },
  { label: "Burundi", value: "Burundi" },
  { label: "Cabo Verde", value: "Cabo Verde" },
  { label: "Cambodia", value: "Cambodia" },
  { label: "Cameroon", value: "Cameroon" },
  { label: "Canada", value: "Canada" },
  { label: "Central African Republic", value: "Central African Republic" },
  { label: "Chad", value: "Chad" },
  { label: "Chile", value: "Chile" },
  { label: "China", value: "China" },
  { label: "Colombia", value: "Colombia" },
  { label: "Comoros", value: "Comoros" },
  { label: "Congo (Congo-Brazzaville)", value: "Congo (Congo-Brazzaville)" },
  { label: "Costa Rica", value: "Costa Rica" },
  { label: "Croatia", value: "Croatia" },
  { label: "Cuba", value: "Cuba" },
  { label: "Cyprus", value: "Cyprus" },
  { label: "Czechia (Czech Republic)", value: "Czechia (Czech Republic)" },
  {
    label: "Democratic Republic of the Congo",
    value: "Democratic Republic of the Congo",
  },
  { label: "Denmark", value: "Denmark" },
  { label: "Djibouti", value: "Djibouti" },
  { label: "Dominica", value: "Dominica" },
  { label: "Dominican Republic", value: "Dominican Republic" },
  { label: "Ecuador", value: "Ecuador" },
  { label: "Egypt", value: "Egypt" },
  { label: "El Salvador", value: "El Salvador" },
  { label: "Equatorial Guinea", value: "Equatorial Guinea" },
  { label: "Eritrea", value: "Eritrea" },
  { label: "Estonia", value: "Estonia" },
  { label: "Eswatini", value: "Eswatini" },
  { label: "Ethiopia", value: "Ethiopia" },
  { label: "Fiji", value: "Fiji" },
  { label: "Finland", value: "Finland" },
  { label: "France", value: "France" },
  { label: "Gabon", value: "Gabon" },
  { label: "Gambia", value: "Gambia" },
  { label: "Georgia", value: "Georgia" },
  { label: "Germany", value: "Germany" },
  { label: "Ghana", value: "Ghana" },
  { label: "Greece", value: "Greece" },
  { label: "Grenada", value: "Grenada" },
  { label: "Guatemala", value: "Guatemala" },
  { label: "Guinea", value: "Guinea" },
  { label: "Guinea-Bissau", value: "Guinea-Bissau" },
  { label: "Guyana", value: "Guyana" },
  { label: "Haiti", value: "Haiti" },
  { label: "Honduras", value: "Honduras" },
  { label: "Hungary", value: "Hungary" },
  { label: "Iceland", value: "Iceland" },
  { label: "India", value: "India" },
  { label: "Indonesia", value: "Indonesia" },
  { label: "Iran", value: "Iran" },
  { label: "Iraq", value: "Iraq" },
  { label: "Ireland", value: "Ireland" },
  { label: "Israel", value: "Israel" },
  { label: "Italy", value: "Italy" },
  { label: "Jamaica", value: "Jamaica" },
  { label: "Japan", value: "Japan" },
  { label: "Jordan", value: "Jordan" },
  { label: "Kazakhstan", value: "Kazakhstan" },
  { label: "Kenya", value: "Kenya" },
  { label: "Kiribati", value: "Kiribati" },
  { label: "Korea, North", value: "Korea, North" },
  { label: "Korea, South", value: "Korea, South" },
  { label: "Kosovo", value: "Kosovo" },
  { label: "Kuwait", value: "Kuwait" },
  { label: "Kyrgyzstan", value: "Kyrgyzstan" },
  { label: "Laos", value: "Laos" },
  { label: "Latvia", value: "Latvia" },
  { label: "Lebanon", value: "Lebanon" },
  { label: "Lesotho", value: "Lesotho" },
  { label: "Liberia", value: "Liberia" },
  { label: "Libya", value: "Libya" },
  { label: "Liechtenstein", value: "Liechtenstein" },
  { label: "Lithuania", value: "Lithuania" },
  { label: "Luxembourg", value: "Luxembourg" },
  { label: "Madagascar", value: "Madagascar" },
  { label: "Malawi", value: "Malawi" },
  { label: "Malaysia", value: "Malaysia" },
  { label: "Maldives", value: "Maldives" },
  { label: "Mali", value: "Mali" },
  { label: "Malta", value: "Malta" },
  { label: "Marshall Islands", value: "Marshall Islands" },
  { label: "Mauritania", value: "Mauritania" },
  { label: "Mauritius", value: "Mauritius" },
  { label: "Mexico", value: "Mexico" },
  { label: "Micronesia", value: "Micronesia" },
  { label: "Moldova", value: "Moldova" },
  { label: "Monaco", value: "Monaco" },
  { label: "Mongolia", value: "Mongolia" },
  { label: "Montenegro", value: "Montenegro" },
  { label: "Morocco", value: "Morocco" },
  { label: "Mozambique", value: "Mozambique" },
  { label: "Myanmar (Burma)", value: "Myanmar (Burma)" },
  { label: "Namibia", value: "Namibia" },
  { label: "Nauru", value: "Nauru" },
  { label: "Nepal", value: "Nepal" },
  { label: "Netherlands", value: "Netherlands" },
  { label: "New Zealand", value: "New Zealand" },
  { label: "Nicaragua", value: "Nicaragua" },
  { label: "Niger", value: "Niger" },
  { label: "Nigeria", value: "Nigeria" },
  { label: "North Macedonia", value: "North Macedonia" },
  { label: "Norway", value: "Norway" },
  { label: "Oman", value: "Oman" },
  { label: "Pakistan", value: "Pakistan" },
  { label: "Palau", value: "Palau" },
  { label: "Palestine", value: "Palestine" },
  { label: "Panama", value: "Panama" },
  { label: "Papua New Guinea", value: "Papua New Guinea" },
  { label: "Paraguay", value: "Paraguay" },
  { label: "Peru", value: "Peru" },
  { label: "Philippines", value: "Philippines" },
  { label: "Poland", value: "Poland" },
  { label: "Portugal", value: "Portugal" },
  { label: "Qatar", value: "Qatar" },
  { label: "Romania", value: "Romania" },
  { label: "Russia", value: "Russia" },
  { label: "Rwanda", value: "Rwanda" },
  { label: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
  { label: "Saint Lucia", value: "Saint Lucia" },
  {
    label: "Saint Vincent and the Grenadines",
    value: "Saint Vincent and the Grenadines",
  },
  { label: "Samoa", value: "Samoa" },
  { label: "San Marino", value: "San Marino" },
  { label: "Sao Tome and Principe", value: "Sao Tome and Principe" },
  { label: "Saudi Arabia", value: "Saudi Arabia" },
  { label: "Senegal", value: "Senegal" },
  { label: "Serbia", value: "Serbia" },
  { label: "Seychelles", value: "Seychelles" },
  { label: "Sierra Leone", value: "Sierra Leone" },
  { label: "Singapore", value: "Singapore" },
  { label: "Slovakia", value: "Slovakia" },
  { label: "Slovenia", value: "Slovenia" },
  { label: "Solomon Islands", value: "Solomon Islands" },
  { label: "Somalia", value: "Somalia" },
  { label: "South Africa", value: "South Africa" },
  { label: "South Sudan", value: "South Sudan" },
  { label: "Spain", value: "Spain" },
  { label: "Sri Lanka", value: "Sri Lanka" },
  { label: "Sudan", value: "Sudan" },
  { label: "Suriname", value: "Suriname" },
  { label: "Sweden", value: "Sweden" },
  { label: "Switzerland", value: "Switzerland" },
  { label: "Syria", value: "Syria" },
  { label: "Taiwan", value: "Taiwan" },
  { label: "Tajikistan", value: "Tajikistan" },
  { label: "Tanzania", value: "Tanzania" },
  { label: "Thailand", value: "Thailand" },
  { label: "Timor-Leste", value: "Timor-Leste" },
  { label: "Togo", value: "Togo" },
  { label: "Tonga", value: "Tonga" },
  { label: "Trinidad and Tobago", value: "Trinidad and Tobago" },
  { label: "Tunisia", value: "Tunisia" },
  { label: "Turkey", value: "Turkey" },
  { label: "Turkmenistan", value: "Turkmenistan" },
  { label: "Tuvalu", value: "Tuvalu" },
  { label: "Uganda", value: "Uganda" },
  { label: "Ukraine", value: "Ukraine" },
  { label: "United Arab Emirates", value: "United Arab Emirates" },
  { label: "United Kingdom", value: "United Kingdom" },
  { label: "United States", value: "United States" },
  { label: "Uruguay", value: "Uruguay" },
  { label: "Uzbekistan", value: "Uzbekistan" },
  { label: "Vanuatu", value: "Vanuatu" },
  { label: "Vatican City", value: "Vatican City" },
  { label: "Venezuela", value: "Venezuela" },
  { label: "Vietnam", value: "Vietnam" },
  { label: "Yemen", value: "Yemen" },
  { label: "Zambia", value: "Zambia" },
  { label: "Zimbabwe", value: "Zimbabwe" },
];

export const PreferredCompanies: Option[] = [
  { label: "Dangote Group", value: "Dangote Group" },
  { label: "MTN Nigeria", value: "MTN Nigeria" },
  { label: "Globacom", value: "Globacom" },
  { label: "Zenith Bank", value: "Zenith Bank" },
  { label: "Access Bank", value: "Access Bank" },
  {
    label: "Guaranty Trust Bank (GTBank)",
    value: "Guaranty Trust Bank (GTBank)",
  },
  { label: "First Bank of Nigeria", value: "First Bank of Nigeria" },
  {
    label: "United Bank for Africa (UBA)",
    value: "United Bank for Africa (UBA)",
  },
  { label: "Airtel Nigeria", value: "Airtel Nigeria" },
  { label: "Nestlé Nigeria", value: "Nestlé Nigeria" },
  { label: "Shell Nigeria", value: "Shell Nigeria" },
  { label: "Chevron Nigeria", value: "Chevron Nigeria" },
  { label: "Total Nigeria", value: "Total Nigeria" },
  {
    label: "NNPC (Nigerian National Petroleum Corporation)",
    value: "NNPC (Nigerian National Petroleum Corporation)",
  },
  { label: "Lafarge Africa", value: "Lafarge Africa" },
  { label: "Julius Berger Nigeria", value: "Julius Berger Nigeria" },
  { label: "Cadbury Nigeria", value: "Cadbury Nigeria" },
  { label: "Unilever Nigeria", value: "Unilever Nigeria" },
  { label: "Interswitch", value: "Interswitch" },
  { label: "Andela", value: "Andela" },
  { label: "Flutterwave", value: "Flutterwave" },
  { label: "Paystack", value: "Paystack" },
  { label: "Konga", value: "Konga" },
  { label: "Jumia Nigeria", value: "Jumia Nigeria" },
  { label: "Microsoft Nigeria", value: "Microsoft Nigeria" },
  { label: "Google Nigeria", value: "Google Nigeria" },
  { label: "Amazon Nigeria", value: "Amazon Nigeria" },
  { label: "Apple Nigeria", value: "Apple Nigeria" },
  { label: "Facebook Nigeria", value: "Facebook Nigeria" },
  { label: "Twitter Nigeria", value: "Twitter Nigeria" },
  { label: "Tesla Nigeria", value: "Tesla Nigeria" },
  { label: "SpaceX Nigeria", value: "SpaceX Nigeria" },
  { label: "IBM Nigeria", value: "IBM Nigeria" },
  { label: "Oracle Nigeria", value: "Oracle Nigeria" },
  { label: "SAP Nigeria", value: "SAP Nigeria" },
  { label: "Intel Nigeria", value: "Intel Nigeria" },
  { label: "Samsung Nigeria", value: "Samsung Nigeria" },
  { label: "Sony Nigeria", value: "Sony Nigeria" },
  { label: "LG Nigeria", value: "LG Nigeria" },
  { label: "Panasonic Nigeria", value: "Panasonic Nigeria" },
  { label: "Toyota Nigeria", value: "Toyota Nigeria" },
  { label: "Honda Nigeria", value: "Honda Nigeria" },
  { label: "Ford Nigeria", value: "Ford Nigeria" },
  { label: "General Motors Nigeria", value: "General Motors Nigeria" },
  { label: "Volkswagen Nigeria", value: "Volkswagen Nigeria" },
  { label: "BMW Nigeria", value: "BMW Nigeria" },
  { label: "Mercedes-Benz Nigeria", value: "Mercedes-Benz Nigeria" },
  { label: "Audi Nigeria", value: "Audi Nigeria" },
  { label: "Porsche Nigeria", value: "Porsche Nigeria" },
  { label: "Ferrari Nigeria", value: "Ferrari Nigeria" },
  { label: "Lamborghini Nigeria", value: "Lamborghini Nigeria" },
  { label: "Rolls-Royce Nigeria", value: "Rolls-Royce Nigeria" },
  { label: "Bentley Nigeria", value: "Bentley Nigeria" },
  { label: "McLaren Nigeria", value: "McLaren Nigeria" },
  { label: "Aston Martin Nigeria", value: "Aston Martin Nigeria" },
  { label: "Jaguar Nigeria", value: "Jaguar Nigeria" },
  { label: "Land Rover Nigeria", value: "Land Rover Nigeria" },
  { label: "Volvo Nigeria", value: "Volvo Nigeria" },
  { label: "Hyundai Nigeria", value: "Hyundai Nigeria" },
  { label: "Kia Nigeria", value: "Kia Nigeria" },
  { label: "Nissan Nigeria", value: "Nissan Nigeria" },
  { label: "Mitsubishi Nigeria", value: "Mitsubishi Nigeria" },
  { label: "Subaru Nigeria", value: "Subaru Nigeria" },
  { label: "Mazda Nigeria", value: "Mazda Nigeria" },
  { label: "Peugeot Nigeria", value: "Peugeot Nigeria" },
  { label: "Renault Nigeria", value: "Renault Nigeria" },
  { label: "Citroën Nigeria", value: "Citroën Nigeria" },
  { label: "Fiat Nigeria", value: "Fiat Nigeria" },
  { label: "Alfa Romeo Nigeria", value: "Alfa Romeo Nigeria" },
  { label: "Maserati Nigeria", value: "Maserati Nigeria" },
  { label: "Bugatti Nigeria", value: "Bugatti Nigeria" },
  { label: "Koenigsegg Nigeria", value: "Koenigsegg Nigeria" },
  { label: "Pagani Nigeria", value: "Pagani Nigeria" },
  { label: "Rimac Nigeria", value: "Rimac Nigeria" },
  { label: "Lotus Nigeria", value: "Lotus Nigeria" },
  { label: "Tata Nigeria", value: "Tata Nigeria" },
  { label: "Mahindra Nigeria", value: "Mahindra Nigeria" },
  { label: "Maruti Suzuki Nigeria", value: "Maruti Suzuki Nigeria" },
  { label: "Hindustan Motors Nigeria", value: "Hindustan Motors Nigeria" },
  { label: "Premier Nigeria", value: "Premier Nigeria" },
  { label: "Force Motors Nigeria", value: "Force Motors Nigeria" },
  { label: "Bajaj Nigeria", value: "Bajaj Nigeria" },
  { label: "TVS Nigeria", value: "TVS Nigeria" },
  { label: "Hero MotoCorp Nigeria", value: "Hero MotoCorp Nigeria" },
  { label: "Royal Enfield Nigeria", value: "Royal Enfield Nigeria" },
  { label: "Yamaha Nigeria", value: "Yamaha Nigeria" },
  { label: "Suzuki Nigeria", value: "Suzuki Nigeria" },
  { label: "Kawasaki Nigeria", value: "Kawasaki Nigeria" },
  { label: "Ducati Nigeria", value: "Ducati Nigeria" },
  { label: "Harley-Davidson Nigeria", value: "Harley-Davidson Nigeria" },
  { label: "Triumph Nigeria", value: "Triumph Nigeria" },
  { label: "KTM Nigeria", value: "KTM Nigeria" },
  { label: "Aprilia Nigeria", value: "Aprilia Nigeria" },
  { label: "Moto Guzzi Nigeria", value: "Moto Guzzi Nigeria" },
  { label: "MV Agusta Nigeria", value: "MV Agusta Nigeria" },
  { label: "Benelli Nigeria", value: "Benelli Nigeria" },
  { label: "Piaggio Nigeria", value: "Piaggio Nigeria" },
  { label: "Vespa Nigeria", value: "Vespa Nigeria" },
  { label: "Lambretta Nigeria", value: "Lambretta Nigeria" },
  { label: "Sym Nigeria", value: "Sym Nigeria" },
  { label: "Keeway Nigeria", value: "Keeway Nigeria" },
  { label: "Zontes Nigeria", value: "Zontes Nigeria" },
  { label: "CFMoto Nigeria", value: "CFMoto Nigeria" },
  { label: "QJ Motor Nigeria", value: "QJ Motor Nigeria" },
  { label: "Brixton Nigeria", value: "Brixton Nigeria" },
  { label: "Fantic Nigeria", value: "Fantic Nigeria" },
  { label: "GasGas Nigeria", value: "GasGas Nigeria" },
  { label: "Husqvarna Nigeria", value: "Husqvarna Nigeria" },
  { label: "Sherco Nigeria", value: "Sherco Nigeria" },
  { label: "Beta Nigeria", value: "Beta Nigeria" },
  { label: "Montesa Nigeria", value: "Montesa Nigeria" },
  { label: "Scorpa Nigeria", value: "Scorpa Nigeria" },
  { label: "Vertigo Nigeria", value: "Vertigo Nigeria" },
  { label: "TM Racing Nigeria", value: "TM Racing Nigeria" },
  { label: "Rieju Nigeria", value: "Rieju Nigeria" },
  { label: "Bultaco Nigeria", value: "Bultaco Nigeria" },
  { label: "Ossa Nigeria", value: "Ossa Nigeria" },
  { label: "Derbi Nigeria", value: "Derbi Nigeria" },
  { label: "Bimota Nigeria", value: "Bimota Nigeria" },
  { label: "Cagiva Nigeria", value: "Cagiva Nigeria" },
  { label: "Gilera Nigeria", value: "Gilera Nigeria" },
  { label: "Italjet Nigeria", value: "Italjet Nigeria" },
  { label: "Laverda Nigeria", value: "Laverda Nigeria" },
  { label: "Morini Nigeria", value: "Morini Nigeria" },
  { label: "Morbidelli Nigeria", value: "Morbidelli Nigeria" },
  { label: "Paton Nigeria", value: "Paton Nigeria" },
  { label: "Vyrus Nigeria", value: "Vyrus Nigeria" },
  { label: "Zongshen Nigeria", value: "Zongshen Nigeria" },
  { label: "Lifan Nigeria", value: "Lifan Nigeria" },
  { label: "Loncin Nigeria", value: "Loncin Nigeria" },
  { label: "Qingqi Nigeria", value: "Qingqi Nigeria" },
  { label: "Shineray Nigeria", value: "Shineray Nigeria" },
  { label: "Skyteam Nigeria", value: "Skyteam Nigeria" },
  { label: "Wuyang Nigeria", value: "Wuyang Nigeria" },
  { label: "Xingyue Nigeria", value: "Xingyue Nigeria" },
  { label: "Yinxiang Nigeria", value: "Yinxiang Nigeria" },
  { label: "Zhongyu Nigeria", value: "Zhongyu Nigeria" },
  { label: "Znen Nigeria", value: "Znen Nigeria" },
  { label: "Zontes Nigeria", value: "Zontes Nigeria" },
  { label: "Zuum Nigeria", value: "Zuum Nigeria" },
  { label: "Zongshen Nigeria", value: "Zongshen Nigeria" },
  { label: "Lifan Nigeria", value: "Lifan Nigeria" },
  { label: "Loncin Nigeria", value: "Loncin Nigeria" },
  { label: "Qingqi Nigeria", value: "Qingqi Nigeria" },
  { label: "Shineray Nigeria", value: "Shineray Nigeria" },
  { label: "Skyteam Nigeria", value: "Skyteam Nigeria" },
  { label: "Wuyang Nigeria", value: "Wuyang Nigeria" },
  { label: "Xingyue Nigeria", value: "Xingyue Nigeria" },
  { label: "Yinxiang Nigeria", value: "Yinxiang Nigeria" },
  { label: "Zhongyu Nigeria", value: "Zhongyu Nigeria" },
  { label: "Znen Nigeria", value: "Znen Nigeria" },
  { label: "Zontes Nigeria", value: "Zontes Nigeria" },
  { label: "Zuum Nigeria", value: "Zuum Nigeria" },
  { label: "Zongshen Nigeria", value: "Zongshen Nigeria" },
  { label: "Lifan Nigeria", value: "Lifan Nigeria" },
  { label: "Loncin Nigeria", value: "Loncin Nigeria" },
  { label: "Qingqi Nigeria", value: "Qingqi Nigeria" },
  { label: "Shineray Nigeria", value: "Shineray Nigeria" },
  { label: "Skyteam Nigeria", value: "Skyteam Nigeria" },
  { label: "Wuyang Nigeria", value: "Wuyang Nigeria" },
  { label: "Xingyue Nigeria", value: "Xingyue Nigeria" },
  { label: "Yinxiang Nigeria", value: "Yinxiang Nigeria" },
  { label: "Zhongyu Nigeria", value: "Zhongyu Nigeria" },
  { label: "Znen Nigeria", value: "Znen Nigeria" },
  { label: "Zontes Nigeria", value: "Zontes Nigeria" },
  { label: "Zuum Nigeria", value: "Zuum Nigeria" },
  { label: "Zongshen Nigeria", value: "Zongshen Nigeria" },
  { label: "Lifan Nigeria", value: "Lifan Nigeria" },
  { label: "Loncin Nigeria", value: "Loncin Nigeria" },
  { label: "Qingqi Nigeria", value: "Qingqi Nigeria" },
  { label: "Shineray Nigeria", value: "Shineray Nigeria" },
  { label: "Skyteam Nigeria", value: "Skyteam Nigeria" },
  { label: "Wuyang Nigeria", value: "Wuyang Nigeria" },
  { label: "Xingyue Nigeria", value: "Xingyue Nigeria" },
  { label: "Yinxiang Nigeria", value: "Yinxiang Nigeria" },
  { label: "Zhongyu Nigeria", value: "Zhongyu Nigeria" },
  { label: "Znen Nigeria", value: "Znen Nigeria" },
  { label: "Zontes Nigeria", value: "Zontes Nigeria" },
  { label: "Zuum Nigeria", value: "Zuum Nigeria" },
  { label: "Zongshen Nigeria", value: "Zongshen Nigeria" },
  { label: "Lifan Nigeria", value: "Lifan Nigeria" },
  { label: "Loncin Nigeria", value: "Loncin Nigeria" },
  { label: "Qingqi Nigeria", value: "Qingqi Nigeria" },
  { label: "Shineray Nigeria", value: "Shineray Nigeria" },
  { label: "Skyteam Nigeria", value: "Skyteam Nigeria" },
  { label: "Wuyang Nigeria", value: "Wuyang Nigeria" },
  { label: "Xingyue Nigeria", value: "Xingyue Nigeria" },
  { label: "Yinxiang Nigeria", value: "Yinxiang Nigeria" },
  { label: "Zhongyu Nigeria", value: "Zhongyu Nigeria" },
  { label: "Znen Nigeria", value: "Znen Nigeria" },
  { label: "Zontes Nigeria", value: "Zontes Nigeria" },
  { label: "Zuum Nigeria", value: "Zuum Nigeria" },
  { label: "Zongshen Nigeria", value: "Zongshen Nigeria" },
  { label: "Lifan Nigeria", value: "Lifan Nigeria" },
  { label: "Loncin Nigeria", value: "Loncin Nigeria" },
  { label: "Qingqi Nigeria", value: "Qingqi Nigeria" },
  { label: "Shineray Nigeria", value: "Shineray Nigeria" },
  { label: "Skyteam Nigeria", value: "Skyteam Nigeria" },
  { label: "Wuyang Nigeria", value: "Wuyang Nigeria" },
  { label: "Xingyue Nigeria", value: "Xingyue Nigeria" },
  { label: "Yinxiang Nigeria", value: "Yinxiang Nigeria" },
  { label: "Zhongyu Nigeria", value: "Zhongyu Nigeria" },
  { label: "Znen Nigeria", value: "Znen Nigeria" },
  { label: "Zontes Nigeria", value: "Zontes Nigeria" },
  { label: "Zuum Nigeria", value: "Zuum Nigeria" },
  { label: "Zongshen Nigeria", value: "Zongshen Nigeria" },
  { label: "Lifan Nigeria", value: "Lifan Nigeria" },
  { label: "Loncin Nigeria", value: "Loncin Nigeria" },
  { label: "Qingqi Nigeria", value: "Qingqi Nigeria" },
  { label: "Shineray Nigeria", value: "Shineray Nigeria" },
  { label: "Skyteam Nigeria", value: "Skyteam Nigeria" },
  { label: "Wuyang Nigeria", value: "Wuyang Nigeria" },
  { label: "Xingyue Nigeria", value: "Xingyue Nigeria" },
  { label: "Yinxiang Nigeria", value: "Yinxiang Nigeria" },
  { label: "Zhongyu Nigeria", value: "Zhongyu Nigeria" },
  { label: "Znen Nigeria", value: "Znen Nigeria" },
  { label: "Zontes Nigeria", value: "Zontes Nigeria" },
  { label: "Zuum Nigeria", value: "Zuum Nigeria" },
  { label: "Zongshen Nigeria", value: "Zongshen Nigeria" },
  { label: "Lifan Nigeria", value: "Lifan Nigeria" },
];

export const universities: Option[] = [
  { label: "Harvard University", value: "Harvard University" },
  { label: "Stanford University", value: "Stanford University" },
  {
    label: "Massachusetts Institute of Technology (MIT)",
    value: "Massachusetts Institute of Technology (MIT)",
  },
  { label: "University of Oxford", value: "University of Oxford" },
  { label: "University of Cambridge", value: "University of Cambridge" },
  {
    label: "California Institute of Technology (Caltech)",
    value: "California Institute of Technology (Caltech)",
  },
  { label: "Princeton University", value: "Princeton University" },
  { label: "University of Chicago", value: "University of Chicago" },
  { label: "Columbia University", value: "Columbia University" },
  { label: "Yale University", value: "Yale University" },
  { label: "University of Pennsylvania", value: "University of Pennsylvania" },
  { label: "Imperial College London", value: "Imperial College London" },
  { label: "ETH Zurich", value: "ETH Zurich" },
  {
    label: "University of California, Berkeley",
    value: "University of California, Berkeley",
  },
  { label: "University of Toronto", value: "University of Toronto" },
  { label: "Johns Hopkins University", value: "Johns Hopkins University" },
  {
    label: "University of California, Los Angeles (UCLA)",
    value: "University of California, Los Angeles (UCLA)",
  },
  {
    label: "UCL (University College London)",
    value: "UCL (University College London)",
  },
  {
    label: "National University of Singapore (NUS)",
    value: "National University of Singapore (NUS)",
  },
  { label: "Peking University", value: "Peking University" },
  { label: "University of Michigan", value: "University of Michigan" },
  { label: "Tsinghua University", value: "Tsinghua University" },
  { label: "Cornell University", value: "Cornell University" },
  { label: "Northwestern University", value: "Northwestern University" },
  { label: "University of Tokyo", value: "University of Tokyo" },
  { label: "New York University (NYU)", value: "New York University (NYU)" },
  { label: "Carnegie Mellon University", value: "Carnegie Mellon University" },
  { label: "University of Hong Kong", value: "University of Hong Kong" },
  { label: "University of Edinburgh", value: "University of Edinburgh" },
  { label: "University of Sydney", value: "University of Sydney" },
  { label: "University of Melbourne", value: "University of Melbourne" },
  { label: "Duke University", value: "Duke University" },
  {
    label: "University of British Columbia",
    value: "University of British Columbia",
  },
  {
    label: "University of Texas at Austin",
    value: "University of Texas at Austin",
  },
  { label: "University of Washington", value: "University of Washington" },
  {
    label: "University of California, San Diego (UCSD)",
    value: "University of California, San Diego (UCSD)",
  },
  {
    label: "Australian National University (ANU)",
    value: "Australian National University (ANU)",
  },
  { label: "University of Queensland", value: "University of Queensland" },
  {
    label: "University of Wisconsin-Madison",
    value: "University of Wisconsin-Madison",
  },
  { label: "KU Leuven", value: "KU Leuven" },
  { label: "University of Copenhagen", value: "University of Copenhagen" },
  { label: "Seoul National University", value: "Seoul National University" },
  {
    label: "Shanghai Jiao Tong University",
    value: "Shanghai Jiao Tong University",
  },
  {
    label: "Ludwig Maximilian University of Munich",
    value: "Ludwig Maximilian University of Munich",
  },
  { label: "Heidelberg University", value: "Heidelberg University" },
  {
    label: "Ecole Polytechnique Fédérale de Lausanne (EPFL)",
    value: "Ecole Polytechnique Fédérale de Lausanne (EPFL)",
  },
  { label: "University of Amsterdam", value: "University of Amsterdam" },
  {
    label: "Hong Kong University of Science and Technology",
    value: "Hong Kong University of Science and Technology",
  },
  {
    label: "University of Southern California",
    value: "University of Southern California",
  },
  {
    label: "University of Illinois Urbana-Champaign",
    value: "University of Illinois Urbana-Champaign",
  },
  { label: "University of Zurich", value: "University of Zurich" },
  { label: "McGill University", value: "McGill University" },
  { label: "Sorbonne University", value: "Sorbonne University" },
  { label: "Monash University", value: "Monash University" },
  {
    label: "Technical University of Munich",
    value: "Technical University of Munich",
  },
  {
    label: "Washington University in St. Louis",
    value: "Washington University in St. Louis",
  },
  {
    label: "University of California, Davis",
    value: "University of California, Davis",
  },
  { label: "Purdue University", value: "Purdue University" },
  {
    label: "University of North Carolina at Chapel Hill",
    value: "University of North Carolina at Chapel Hill",
  },
  { label: "Boston University", value: "Boston University" },
  { label: "University of Minnesota", value: "University of Minnesota" },
  {
    label: "University of Maryland, College Park",
    value: "University of Maryland, College Park",
  },
  { label: "King's College London", value: "King's College London" },
  {
    label: "Pennsylvania State University",
    value: "Pennsylvania State University",
  },
  { label: "The Ohio State University", value: "The Ohio State University" },
  { label: "University of Geneva", value: "University of Geneva" },
  { label: "Osaka University", value: "Osaka University" },
  {
    label: "Tokyo Institute of Technology",
    value: "Tokyo Institute of Technology",
  },
  { label: "University of Groningen", value: "University of Groningen" },
  { label: "University of Bristol", value: "University of Bristol" },
  { label: "University of Glasgow", value: "University of Glasgow" },
  {
    label: "Vrije Universiteit Amsterdam",
    value: "Vrije Universiteit Amsterdam",
  },
  { label: "University of Helsinki", value: "University of Helsinki" },
  { label: "University of Auckland", value: "University of Auckland" },
  { label: "Kyoto University", value: "Kyoto University" },
  { label: "Rice University", value: "Rice University" },
  { label: "University of Alberta", value: "University of Alberta" },
  {
    label: "Delft University of Technology",
    value: "Delft University of Technology",
  },
  { label: "Université de Montréal", value: "Université de Montréal" },
  { label: "Stockholm University", value: "Stockholm University" },
  { label: "RWTH Aachen University", value: "RWTH Aachen University" },
  {
    label: "Indian Institute of Science (IISc)",
    value: "Indian Institute of Science (IISc)",
  },
  { label: "University of Oslo", value: "University of Oslo" },
  { label: "National Taiwan University", value: "National Taiwan University" },
  { label: "University of St Andrews", value: "University of St Andrews" },
];

export const currencies: Option[] = [
  { label: "USD", value: "$" }, // United States Dollar
  { label: "EUR", value: "€" }, // Euro
  { label: "GBP", value: "£" }, // British Pound Sterling
  { label: "JPY", value: "¥" }, // Japanese Yen
  { label: "AUD", value: "$" }, // Australian Dollar
  { label: "CAD", value: "$" }, // Canadian Dollar
  { label: "CHF", value: "CHF" }, // Swiss Franc
  { label: "CNY", value: "¥" }, // Chinese Yuan
  { label: "SEK", value: "kr" }, // Swedish Krona
  { label: "NZD", value: "$" }, // New Zealand Dollar
  { label: "MXN", value: "$" }, // Mexican Peso
  { label: "SGD", value: "$" }, // Singapore Dollar
  { label: "HKD", value: "$" }, // Hong Kong Dollar
  { label: "NOK", value: "kr" }, // Norwegian Krone
  { label: "KRW", value: "₩" }, // South Korean Won
  { label: "TRY", value: "₺" }, // Turkish Lira
  { label: "INR", value: "₹" }, // Indian Rupee
  { label: "BRL", value: "R$" }, // Brazilian Real
  { label: "ZAR", value: "R" }, // South African Rand
  { label: "PHP", value: "₱" }, // Philippine Peso
  { label: "CZK", value: "Kč" }, // Czech Koruna
  { label: "IDR", value: "Rp" }, // Indonesian Rupiah
  { label: "MYR", value: "RM" }, // Malaysian Ringgit
  { label: "HUF", value: "Ft" }, // Hungarian Forint
  { label: "ISK", value: "kr" }, // Icelandic Krona
  { label: "DKK", value: "kr" }, // Danish Krone
  { label: "THB", value: "฿" }, // Thai Baht
  { label: "PLN", value: "zł" }, // Polish Zloty
  { label: "ARS", value: "$" }, // Argentine Peso
  { label: "COP", value: "$" }, // Colombian Peso
  { label: "CLP", value: "$" }, // Chilean Peso
  { label: "SAR", value: "﷼" }, // Saudi Riyal
  { label: "AED", value: "د.إ" }, // United Arab Emirates Dirham
  { label: "ILS", value: "₪" }, // Israeli New Shekel
  { label: "VND", value: "₫" }, // Vietnamese Dong
  { label: "EGP", value: "£" }, // Egyptian Pound
  { label: "NGN", value: "₦" }, // Nigerian Naira
  { label: "PKR", value: "₨" }, // Pakistani Rupee
  { label: "PEN", value: "S/." }, // Peruvian Sol
];
