interface Option {
  value: string;
  label: string;
}

export const DepartmentType: Option[] = [
  { value: "Engineering", label: "Engineering" },
  { value: "Software_Development", label: "Software Development" },
  { value: "Data_Science", label: "Data Science" },
  { value: "Product_Management", label: "Product Management" },
  { value: "Marketing", label: "Marketing" },
  { value: "Sales", label: "Sales" },
  { value: "Human_Resources", label: "Human Resources" },
  { value: "Finance", label: "Finance" },
  { value: "Accounting", label: "Accounting" },
  { value: "Customer_Support", label: "Customer Support" },
  { value: "Information_Technology", label: "Information Technology" },
  { value: "Design", label: "Design" },
  { value: "UX_UI", label: "UX/UI" },
  { value: "Operations", label: "Operations" },
  { value: "Supply_Chain", label: "Supply Chain" },
  { value: "Logistics", label: "Logistics" },
  { value: "Research_Development", label: "Research & Development" },
  { value: "Legal", label: "Legal" },
  { value: "Compliance", label: "Compliance" },
  { value: "Risk_Management", label: "Risk Management" },
  { value: "Corporate_Communications", label: "Corporate Communications" },
  { value: "Business_Development", label: "Business Development" },
  { value: "Strategy", label: "Strategy" },
  { value: "Quality_Assurance", label: "Quality Assurance" },
  { value: "Security", label: "Security" },
  { value: "Facilities_Management", label: "Facilities Management" },
  { value: "Training_Development", label: "Training & Development" },
  { value: "Procurement", label: "Procurement" },
  { value: "Technical_Support", label: "Technical Support" },
  { value: "Investor_Relations", label: "Investor Relations" },
  { value: "Public_Relations", label: "Public Relations" },
  { value: "Medical", label: "Medical" },
  { value: "Healthcare", label: "Healthcare" },
  { value: "Content_Creation", label: "Content Creation" },
  { value: "Editorial", label: "Editorial" },
  { value: "Animation", label: "Animation" },
  { value: "Game_Development", label: "Game Development" },
  { value: "Customer_Success", label: "Customer Success" },
  { value: "Data_Engineering", label: "Data Engineering" },
  { value: "DevOps", label: "DevOps" },
  { value: "Cloud_Infrastructure", label: "Cloud Infrastructure" },
  { value: "Analytics", label: "Analytics" },
  { value: "Machine_Learning", label: "Machine Learning" },
  { value: "AI_Research", label: "AI Research" },
  { value: "Education", label: "Education" },
  { value: "Administration", label: "Administration" },
  { value: "Event_Management", label: "Event Management" },
];

export const EmploymentType: Option[] = [
  { value: "Onsite", label: "Onsite" },
  { value: "Remote", label: "Remote" },
  { value: "Hybrid", label: "Hybrid" },
];
