import {Option} from "../components/ui/applicant/profile/Skills.tsx";

export interface MessageItem {
    id: number;
    avatar: string; // Avatar URL or path
    name: string;
    message: string;
    time: string;
}

export const messages: MessageItem[] = [
    {
        id: 1,
        avatar: "https://via.placeholder.com/40", // Replace with actual avatar URL
        name: "A.S Abubakar",
        message: "Your job with us is more of...",
        time: "2 hours ago",
    },
    {
        id: 2,
        avatar: "https://via.placeholder.com/40", // Replace with actual avatar URL
        name: "Umar M Ahmad",
        message: "Your job with us is more of...",
        time: "2 hours ago",
    },
    {
        id: 3,
        avatar: "https://via.placeholder.com/40", // Replace with actual avatar URL
        name: "Jawad Umar",
        message: "Your job with us is more of...",
        time: "2 hours ago",
    },
    {
        id: 4,
        avatar: "https://via.placeholder.com/40", // Replace with actual avatar URL
        name: "David Rose",
        message: "Your job with us is more of...",
        time: "2 hours ago",
    },
    {
        id: 5,
        avatar: "https://via.placeholder.com/40", // Replace with actual avatar URL
        name: "Khadija Umar",
        message: "Your job with us is more of...",
        time: "2 days ago",
    },
];

export const skills: Option[] = [
    { label: "Java", value: "Java" },
    { label: "Python", value: "Python" },
    { label: "JavaScript", value: "JavaScript" },
    { label: "C++", value: "C++" },
    { label: "React", value: "React" },
    { label: "Node.js", value: "Node.js" },
    { label: "TypeScript", value: "TypeScript" },
    { label: "SQL", value: "SQL" },
    { label: "Docker", value: "Docker" },
    { label: "AWS", value: "AWS" },
    { label: "Kubernetes", value: "Kubernetes" },
    { label: "Git", value: "Git" },
    { label: "GitHub", value: "GitHub" },
    { label: "GitLab", value: "GitLab" },
    { label: "HTML", value: "HTML" },
    { label: "CSS", value: "CSS" },
    { label: "SASS", value: "SASS" },
    { label: "Bootstrap", value: "Bootstrap" },
    { label: "Tailwind CSS", value: "Tailwind CSS" },
    { label: "Angular", value: "Angular" },
    { label: "Vue.js", value: "Vue.js" },
    { label: "Next.js", value: "Next.js" },
    { label: "GraphQL", value: "GraphQL" },
    { label: "REST API", value: "REST API" },
    { label: "PostgreSQL", value: "PostgreSQL" },
    { label: "MongoDB", value: "MongoDB" },
    { label: "Firebase", value: "Firebase" },
    { label: "Redis", value: "Redis" },
    { label: "Elasticsearch", value: "Elasticsearch" },
    { label: "Jenkins", value: "Jenkins" },
    { label: "CI/CD", value: "CI/CD" },
    { label: "Terraform", value: "Terraform" },
    { label: "Ansible", value: "Ansible" },
    { label: "Linux", value: "Linux" },
    { label: "Bash", value: "Bash" },
    { label: "Shell Scripting", value: "Shell Scripting" },
    { label: "Agile", value: "Agile" },
    { label: "Scrum", value: "Scrum" },
    { label: "Kanban", value: "Kanban" },
    { label: "Jira", value: "Jira" },
    { label: "Confluence", value: "Confluence" },
    { label: "Figma", value: "Figma" },
    { label: "Adobe XD", value: "Adobe XD" },
    { label: "Sketch", value: "Sketch" },
    { label: "Unity", value: "Unity" },
    { label: "Unreal Engine", value: "Unreal Engine" },
    { label: "Blender", value: "Blender" },
    { label: "3D Modeling", value: "3D Modeling" },
    { label: "AR/VR", value: "AR/VR" },
    { label: "Machine Learning", value: "Machine Learning" },
    { label: "Deep Learning", value: "Deep Learning" },
    { label: "TensorFlow", value: "TensorFlow" },
    { label: "PyTorch", value: "PyTorch" },
    { label: "Pandas", value: "Pandas" },
    { label: "NumPy", value: "NumPy" },
    { label: "SciPy", value: "SciPy" },
    { label: "Matplotlib", value: "Matplotlib" },
    { label: "Seaborn", value: "Seaborn" },
    { label: "Tableau", value: "Tableau" },
    { label: "Power BI", value: "Power BI" },
    { label: "Excel", value: "Excel" },
    { label: "Google Sheets", value: "Google Sheets" },
    { label: "Data Analysis", value: "Data Analysis" },
    { label: "Data Visualization", value: "Data Visualization" },
    { label: "Big Data", value: "Big Data" },
    { label: "Hadoop", value: "Hadoop" },
    { label: "Spark", value: "Spark" },
    { label: "Kafka", value: "Kafka" },
    { label: "RabbitMQ", value: "RabbitMQ" },
    { label: "Microservices", value: "Microservices" },
    { label: "Serverless", value: "Serverless" },
    { label: "Lambda", value: "Lambda" },
    { label: "Azure", value: "Azure" },
    { label: "Google Cloud", value: "Google Cloud" },
    { label: "Heroku", value: "Heroku" },
    { label: "Netlify", value: "Netlify" },
    { label: "Vercel", value: "Vercel" },
    { label: "Webpack", value: "Webpack" },
    { label: "Babel", value: "Babel" },
    { label: "ESLint", value: "ESLint" },
    { label: "Prettier", value: "Prettier" },
    { label: "Jest", value: "Jest" },
    { label: "Cypress", value: "Cypress" },
    { label: "Selenium", value: "Selenium" },
    { label: "Testing", value: "Testing" },
    { label: "DevOps", value: "DevOps" },
    { label: "Security", value: "Security" },
    { label: "OAuth", value: "OAuth" },
    { label: "JWT", value: "JWT" },
    { label: "Blockchain", value: "Blockchain" },
    { label: "Smart Contracts", value: "Smart Contracts" },
    { label: "Solidity", value: "Solidity" },
    { label: "Ethereum", value: "Ethereum" },
    { label: "Bitcoin", value: "Bitcoin" },
    { label: "Cryptography", value: "Cryptography" },
    { label: "Rust", value: "Rust" },
    { label: "Go", value: "Go" },
    { label: "Ruby", value: "Ruby" },
    { label: "PHP", value: "PHP" },
    { label: "Swift", value: "Swift" },
    { label: "Kotlin", value: "Kotlin" },
    { label: "Flutter", value: "Flutter" },
    { label: "Dart", value: "Dart" },
    { label: "React Native", value: "React Native" },
    { label: "Xamarin", value: "Xamarin" },
];