interface Option {
  value: string;
  label: string;
}

export const JobType: Option[] = [
  { value: "Full Time", label: "Full Time" },
  { value: "Part Time", label: "Part Time" },
  { value: "Contract", label: "Contract" },
  { value: "Freelance", label: "Freelance" },
  { value: "Internship", label: "Internship" },
  { value: "Apprenticeship", label: "Apprenticeship" },
  { value: "Consultant", label: "Consultant" },
  { value: "Temporary", label: "Temporary" },
  { value: "Volunteer", label: "Volunteer" },
];

export const JobLocations: Option[] = [
  { value: "Abu_Dhabi", label: "Abu Dhabi, UAE" },
  { value: "Amsterdam", label: "Amsterdam, Netherlands" },
  { value: "Atlanta", label: "Atlanta, USA" },
  { value: "Bangalore", label: "Bangalore, India" },
  { value: "Barcelona", label: "Barcelona, Spain" },
  { value: "Beijing", label: "Beijing, China" },
  { value: "Berlin", label: "Berlin, Germany" },
  { value: "Birmingham", label: "Birmingham, UK" },
  { value: "Boston", label: "Boston, USA" },
  { value: "Brussels", label: "Brussels, Belgium" },
  { value: "Budapest", label: "Budapest, Hungary" },
  { value: "Buenos_Aires", label: "Buenos Aires, Argentina" },
  { value: "Cape_Town", label: "Cape Town, South Africa" },
  { value: "Chicago", label: "Chicago, USA" },
  { value: "Copenhagen", label: "Copenhagen, Denmark" },
  { value: "Dallas", label: "Dallas, USA" },
  { value: "Delhi", label: "Delhi, India" },
  { value: "Dubai", label: "Dubai, UAE" },
  { value: "Dublin", label: "Dublin, Ireland" },
  { value: "Edinburgh", label: "Edinburgh, UK" },
  { value: "Helsinki", label: "Helsinki, Finland" },
  { value: "Hong_Kong", label: "Hong Kong" },
  { value: "Houston", label: "Houston, USA" },
  { value: "Istanbul", label: "Istanbul, Turkey" },
  { value: "Johannesburg", label: "Johannesburg, South Africa" },
  { value: "Lagos", label: "Lagos, Nigeria" },
  { value: "London", label: "London, UK" },
  { value: "Los_Angeles", label: "Los Angeles, USA" },
  { value: "Madrid", label: "Madrid, Spain" },
  { value: "Manchester", label: "Manchester, UK" },
  { value: "Melbourne", label: "Melbourne, Australia" },
  { value: "Mexico_City", label: "Mexico City, Mexico" },
  { value: "Miami", label: "Miami, USA" },
  { value: "Milan", label: "Milan, Italy" },
  { value: "Montreal", label: "Montreal, Canada" },
  { value: "Moscow", label: "Moscow, Russia" },
  { value: "Mumbai", label: "Mumbai, India" },
  { value: "Munich", label: "Munich, Germany" },
  { value: "Nairobi", label: "Nairobi, Kenya" },
  { value: "New_York", label: "New York, USA" },
  { value: "Oslo", label: "Oslo, Norway" },
  { value: "Paris", label: "Paris, France" },
  { value: "Prague", label: "Prague, Czech Republic" },
  { value: "Rome", label: "Rome, Italy" },
  { value: "San_Francisco", label: "San Francisco, USA" },
  { value: "Sao_Paulo", label: "São Paulo, Brazil" },
  { value: "Seattle", label: "Seattle, USA" },
  { value: "Shanghai", label: "Shanghai, China" },
  { value: "Singapore", label: "Singapore" },
  { value: "Stockholm", label: "Stockholm, Sweden" },
  { value: "Sydney", label: "Sydney, Australia" },
  { value: "Tokyo", label: "Tokyo, Japan" },
  { value: "Toronto", label: "Toronto, Canada" },
  { value: "Vancouver", label: "Vancouver, Canada" },
  { value: "Vienna", label: "Vienna, Austria" },
  { value: "Warsaw", label: "Warsaw, Poland" },
  { value: "Zurich", label: "Zurich, Switzerland" },
];

export const jobSkills: string[] = [
  "Active Listening",
  "Adaptability & Flexibility",
  "Analytical Thinking",
  "Attention to Detail",
  "Brainstorming",
  "Change Management",
  "Collaboration",
  "Communication (Written & Verbal)",
  "Conflict Resolution",
  "Creative Problem Solving",
  "Critical Thinking",
  "Customer Service",
  "Decision-Making",
  "Dependability & Work Ethic",
  "Emotional Intelligence",
  "Empathy",
  "Goal Setting",
  "Initiative",
  "Interpersonal Skills",
  "Leadership",
  "Lifelong Learning",
  "Mentoring & Coaching",
  "Motivation",
  "Negotiation",
  "Organizational Skills",
  "Patience",
  "Persuasion",
  "Planning & Prioritization",
  "Presentation Skills",
  "Public Speaking",
  "Project Management (General)",
  "Problem-Solving",
  "Relationship Building",
  "Resilience",
  "Research & Information Synthesis",
  "Resourcefulness",
  "Self-Management",
  "Strategic Thinking",
  "Teamwork",
  "Time Management",
  "Training & Development",
  "Troubleshooting",
  "A/B Testing",
  "API Development (REST, GraphQL)",
  "B2B Sales",
  "B2C Sales",
  "Business Analysis",
  "Business Intelligence (BI)",
  "Cloud Computing (AWS, Azure, GCP)",
  "Command Line Interface (CLI)",
  "Competitive Analysis",
  "Computer Vision",
  "Content Management Systems (CMS)",
  "Content Marketing",
  "Conversion Rate Optimization (CRO)",
  "Copywriting",
  "CRM Management",
  "Data Analysis",
  "Data Governance",
  "Data Mining",
  "Data Modeling",
  "Data Processing",
  "Data Visualization (Tableau, Power BI, Matplotlib)",
  "Database Management (SQL, NoSQL, MongoDB, PostgreSQL, MySQL)",
  "Deep Learning",
  "DevOps",
  "Digital Marketing",
  "Docker",
  "E-commerce Operations",
  "Email Marketing",
  "Embedded Systems",
  "Feasibility Studies",
  "Financial Forecasting",
  "Financial Modeling",
  "Figma",
  "Firewall Configuration",
  "Git/GitHub",
  "Google Ads (PPC)",
  "Google Analytics",
  "Graphic Design (Adobe Suite, Canva)",
  "Human Resources Information Systems (HRIS)",
  "Influencer Marketing",
  "Inventory Management",
  "IT Support",
  "Jira & Trello",
  "Kubernetes",
  "Lean Six Sigma",
  "Lead Generation",
  "Linux/Windows Server Administration",
  "Logistics",
  "Machine Learning",
  "Market Research",
  "Marketing Automation",
  "Microservices Architecture",
  "Motion Graphics",
  "Natural Language Processing (NLP)",
  "Network Administration",
  "Onboarding Processes",
  "Organizational Development",
  "Payroll Management",
  "Performance Management",
  "Predictive Modeling",
  "Procurement",
  "Product Management (General)",
  "Product Strategy",
  "Proposal Writing",
  "Prototyping",
  "Recruitment & Talent Acquisition",
  "Risk Management",
  "Robotics",
  "Roadmap Planning",
  "Sales Forecasting",
  "Salesforce",
  "Scrum & Agile Methodologies",
  "SEO (Search Engine Optimization)",
  "Social Media Marketing & Management",
  "Statistical Analysis",
  "Supply Chain Management",
  "Systems Engineering",
  "Tax Compliance",
  "Technical Support",
  "Time Series Forecasting",
  "User Research",
  "User Testing",
  "UX/UI Design",
  "Vendor Management",
  "VPN Configuration",
  "Warehouse Management",
  "Wireframing",
  ".NET Core",
  "Angular",
  "C#",
  "C++",
  "Django",
  "Flask",
  "Go",
  "Java",
  "JavaScript",
  "Kotlin",
  "MATLAB",
  "Next.js",
  "Node.js",
  "Python (Pandas, NumPy, Scikit-Learn)",
  "PyTorch",
  "R Programming",
  "React",
  "Ruby on Rails",
  "Rust",
  "Swift",
  "TensorFlow",
  "TypeScript",
  "Vue.js",
  "Adobe XD",
  "AutoCAD",
  "Docker",
  "Firebase",
  "Freshdesk",
  "Hadoop",
  "HubSpot",
  "Kafka",
  "Marketo",
  "MongoDB",
  "MS Excel (Advanced)",
  "MS Office Suite",
  "MySQL",
  "Power BI",
  "PostgreSQL",
  "Salesforce",
  "Sketch",
  "SolidWorks",
  "Spark",
  "Tableau",
  "Zendesk",
];
