interface Option {
    value: string;
    label: string;
  }

export const JobType: Option[] = [
    { value: "Contract", label: "Contract" },
    { value: "Freelance", label: "Freelance" },
    { value: "Internship", label: "Internship" },
    { value: "Temporary", label: "Temporary" },
    { value: "Volunteer", label: "Volunteer" },
    { value: "Seasonal", label: "Seasonal" },
    { value: "Consultant", label: "Consultant" },
    { value: "Apprenticeship", label: "Apprenticeship" },
  ];

  export const JobLocations: Option[] = [

    { value: "Abu_Dhabi", label: "Abu Dhabi, UAE" },
    { value: "Amsterdam", label: "Amsterdam, Netherlands" },
    { value: "Atlanta", label: "Atlanta, USA" },
    { value: "Bangalore", label: "Bangalore, India" },
    { value: "Barcelona", label: "Barcelona, Spain" },
    { value: "Beijing", label: "Beijing, China" },
    { value: "Berlin", label: "Berlin, Germany" },
    { value: "Birmingham", label: "Birmingham, UK" },
    { value: "Boston", label: "Boston, USA" },
    { value: "Brussels", label: "Brussels, Belgium" },
    { value: "Budapest", label: "Budapest, Hungary" },
    { value: "Buenos_Aires", label: "Buenos Aires, Argentina" },
    { value: "Cape_Town", label: "Cape Town, South Africa" },
    { value: "Chicago", label: "Chicago, USA" },
    { value: "Copenhagen", label: "Copenhagen, Denmark" },
    { value: "Dallas", label: "Dallas, USA" },
    { value: "Delhi", label: "Delhi, India" },
    { value: "Dubai", label: "Dubai, UAE" },
    { value: "Dublin", label: "Dublin, Ireland" },
    { value: "Edinburgh", label: "Edinburgh, UK" },
    { value: "Helsinki", label: "Helsinki, Finland" },
    { value: "Hong_Kong", label: "Hong Kong" },
    { value: "Houston", label: "Houston, USA" },
    { value: "Istanbul", label: "Istanbul, Turkey" },
    { value: "Johannesburg", label: "Johannesburg, South Africa" },
    { value: "Lagos", label: "Lagos, Nigeria" },
    { value: "London", label: "London, UK" },
    { value: "Los_Angeles", label: "Los Angeles, USA" },
    { value: "Madrid", label: "Madrid, Spain" },
    { value: "Manchester", label: "Manchester, UK" },
    { value: "Melbourne", label: "Melbourne, Australia" },
    { value: "Mexico_City", label: "Mexico City, Mexico" },
    { value: "Miami", label: "Miami, USA" },
    { value: "Milan", label: "Milan, Italy" },
    { value: "Montreal", label: "Montreal, Canada" },
    { value: "Moscow", label: "Moscow, Russia" },
    { value: "Mumbai", label: "Mumbai, India" },
    { value: "Munich", label: "Munich, Germany" },
    { value: "Nairobi", label: "Nairobi, Kenya" },
    { value: "New_York", label: "New York, USA" },
    { value: "Oslo", label: "Oslo, Norway" },
    { value: "Paris", label: "Paris, France" },
    { value: "Prague", label: "Prague, Czech Republic" },
    { value: "Rome", label: "Rome, Italy" },
    { value: "San_Francisco", label: "San Francisco, USA" },
    { value: "Sao_Paulo", label: "São Paulo, Brazil" },
    { value: "Seattle", label: "Seattle, USA" },
    { value: "Shanghai", label: "Shanghai, China" },
    { value: "Singapore", label: "Singapore" },
    { value: "Stockholm", label: "Stockholm, Sweden" },
    { value: "Sydney", label: "Sydney, Australia" },
    { value: "Tokyo", label: "Tokyo, Japan" },
    { value: "Toronto", label: "Toronto, Canada" },
    { value: "Vancouver", label: "Vancouver, Canada" },
    { value: "Vienna", label: "Vienna, Austria" },
    { value: "Warsaw", label: "Warsaw, Poland" },
    { value: "Zurich", label: "Zurich, Switzerland" },    
];

export const jobSkills: string[] = [
    "Systems Engineering", "Mechanical Engineering", "Electrical Engineering", "Civil Engineering", "Industrial Automation", 
    "Embedded Systems", "Control Systems", "Robotics", "CAD (AutoCAD, SolidWorks)", "Finite Element Analysis (FEA)", "MATLAB",
    "JavaScript", "TypeScript", "React", "Angular", "Vue.js", "Next.js", "Node.js", "Python", "Java", "C#", "C++", "Go", "Rust", 
    "Swift", "Kotlin", "Ruby on Rails", "Django", "Flask", ".NET Core", "GraphQL", "REST API Development", "Docker", "Kubernetes", 
    "Microservices", "Firebase", "MongoDB", "PostgreSQL", "MySQL", "Agile Methodologies", "Git/GitHub", "CI/CD Pipelines",
    "Python (Pandas, NumPy)", "R Programming", "SQL", "Machine Learning (Scikit-Learn, TensorFlow, PyTorch)", "Deep Learning", 
    "Data Visualization (Matplotlib, Seaborn, Power BI, Tableau)", "Big Data (Hadoop, Spark, Kafka)", "Data Warehousing", 
    "Cloud Computing (AWS, Azure, GCP)", "Natural Language Processing (NLP)", "Computer Vision", "Statistical Analysis", 
    "Predictive Modeling", "Time Series Forecasting",
    "Agile & Scrum", "Roadmap Planning", "Product Strategy", "Market Research", "UX/UI Understanding", "Wireframing & Prototyping", 
    "User Testing", "Business Analysis", "A/B Testing", "KPI & Metrics Tracking", "Competitive Analysis", "Stakeholder Communication", 
    "Jira & Trello",
    "SEO (Search Engine Optimization)", "SEM (Google Ads, PPC)", "Content Marketing", "Social Media Management", "Copywriting", 
    "Email Marketing", "Marketing Automation (HubSpot, Marketo)", "Influencer Marketing", "Google Analytics", "CRM Management", 
    "Branding & Positioning", "Market Research", "Conversion Rate Optimization (CRO)", "Facebook & Instagram Ads", "LinkedIn Ads",
    "Cold Calling", "Lead Generation", "CRM Tools (Salesforce, HubSpot)", "Negotiation", "Customer Relationship Management", 
    "Sales Forecasting", "B2B Sales", "B2C Sales", "Account Management", "Proposal Writing", "Public Speaking", "Sales Presentations",
    "Recruitment & Talent Acquisition", "Onboarding Processes", "Employee Relations", "Performance Management", "HR Compliance & Labor Laws", 
    "Compensation & Benefits", "Organizational Development", "Training & Development", "Conflict Resolution", "Diversity & Inclusion",
    "Financial Modeling", "Budgeting & Forecasting", "Accounting Principles (GAAP, IFRS)", "Tax Compliance", "Investment Analysis", 
    "Auditing", "Risk Management", "Financial Reporting", "Payroll Management",
    "Customer Service", "Ticket Management (Zendesk, Freshdesk)", "Call Center Operations", "Technical Support", "Conflict Resolution", 
    "Live Chat & Email Support", "CRM Knowledge",
    "Network Administration", "Cybersecurity", "Cloud Computing (AWS, Azure, GCP)", "IT Support & Troubleshooting", 
    "Linux/Windows Server Management", "VPN & Firewall Configuration", "IT Compliance & Governance", "Data Backup & Recovery",
    "Graphic Design", "UX/UI Design", "Figma", "Adobe XD", "Sketch", "Prototyping", "User Research", "Interaction Design", "Motion Graphics",
    "Inventory Management", "Warehouse Management", "Logistics Coordination", "Supply Chain Optimization", "Procurement & Vendor Management", 
    "Shipping & Freight Management", "Lean Six Sigma",
    "Scientific Research", "Experimentation & Testing", "Intellectual Property (IP) Management", "Market & Consumer Research", 
    "New Product Development (NPD)"
  ];
  