export { default as Person1 } from "./images/image1.png";
export { default as Person2 } from "./images/image2.png";
export { default as Person3 } from "./images/image3.png";
export { default as Person4 } from "./images/image4.png";
export { default as Person5 } from "./images/image5.png";
export { default as Person6 } from "./images/image6.png";
export { default as Person7 } from "./images/image7.png";
export { default as Testimonial } from "./images/testimonial.png";
export { default as Human1 } from "./images/human1.png";
export { default as Referrer1 } from "./images/referrer1.svg";
export { default as Referrer2 } from "./images/referrer2.svg";
export { default as Referrer3 } from "./images/referrer3.svg";
export { default as Crown } from "./images/crown.svg";
export { default as ArrowLeft2 } from "./images/arrow-left-02.png";
export { default as ASAbubakar } from "./images/As abubakar.svg";
export { default as Worksample1 } from "./images/worksample1.svg";
export { default as Worksample2 } from "./images/worksample2.svg";
export { default as Attachment } from "./images/attachment.svg";
export { default as ImageUpload } from "./images/image upload.svg";
export { default as Bagged } from "./images/bagged.svg";
export { default as Ellipse115 } from "./images/Ellipse 115.svg";
export { default as Ellipse116 } from "./images/Ellipse 116.svg";
export { default as Ellipse117 } from "./images/Ellipse 117.svg";
